// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE6cWNGt8dvVMXMBDAhPVmkXFvMXl4fbs',
    appId: '1:221659583938:web:f8ed011bb622a546b3725b',
    messagingSenderId: '221659583938',
    projectId: 'meddoc-bfe57',
    authDomain: 'meddoc-bfe57.firebaseapp.com',
    storageBucket: 'meddoc-bfe57.firebasestorage.app',
    measurementId: 'G-VQBSCWHH7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrf4G_dnQDwbrCdp0Kz7UWQs57-C16J4Q',
    appId: '1:221659583938:android:f71f9fa363e7a3acb3725b',
    messagingSenderId: '221659583938',
    projectId: 'meddoc-bfe57',
    storageBucket: 'meddoc-bfe57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGd9i8Hz_QkD5p4xUlyFGJTJeJFhx6iCo',
    appId: '1:221659583938:ios:8448764e3cd0430fb3725b',
    messagingSenderId: '221659583938',
    projectId: 'meddoc-bfe57',
    storageBucket: 'meddoc-bfe57.firebasestorage.app',
    iosBundleId: 'com.example.meddoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGd9i8Hz_QkD5p4xUlyFGJTJeJFhx6iCo',
    appId: '1:221659583938:ios:8448764e3cd0430fb3725b',
    messagingSenderId: '221659583938',
    projectId: 'meddoc-bfe57',
    storageBucket: 'meddoc-bfe57.firebasestorage.app',
    iosBundleId: 'com.example.meddoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE6cWNGt8dvVMXMBDAhPVmkXFvMXl4fbs',
    appId: '1:221659583938:web:6fc3144674d513a8b3725b',
    messagingSenderId: '221659583938',
    projectId: 'meddoc-bfe57',
    authDomain: 'meddoc-bfe57.firebaseapp.com',
    storageBucket: 'meddoc-bfe57.firebasestorage.app',
    measurementId: 'G-HJ4Q1FJ611',
  );
}
